name: auto_login
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.10+10

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.0
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.0.9
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  flutter_foreground_task: ^6.1.2
  fl_location: ^3.0.0
  permission_handler: ^11.1.0
  latlong2: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
